### ISSUE TITLE
Focus topic discussion

### ISSUE THREAD

**Issue by booyaa** [rust-community/content-team#16]
We’re looking for good focus topic to get the ball rolling for our next blogging campaign. I’ll start the ball rolling with my ideas:

- Something WASMy (surprise)
- Rust bridge workshop POV for trainers and trainees

Please suggest any more in comments. I will discuss this issue and [content-o-tron](https://github.com/rust-community)  at our next community meeting.

**Comment by skade** [comment]
* Embedded

I meet more and more people actually doing that but never writing about it.

**Comment by aturon** [comment]
- Great crates that you've used, and why they're great
- Crates you'd like to see reach 1.0
- Rust design patterns
- Structuring a large app in Rust
- Walkthrough of a small crate
- How to make your Rust workflow awesome

**Comment by wezm** [comment]
* How you're deploying Rust to production
* Approaches/patterns for testing Rust applications

**Comment by skade** [comment]
* Rust in the enterprise

**Comment by booyaa** [comment]
Thanks for all the great ideas, I've copied this over to the following [document](https://github.com/rust-community/content-o-tron/blob/master/guides/blogpost_topics.md) in Content-o-Tron.
