### ISSUE TITLE
Agenda: 8th May 2018

### ISSUE THREAD

**Issue by booyaa** [rust-community/content-team#28]
Please note we've moved back to the main community channel (`#rust-community`) to increase our reach. Once we've reached sufficient momentum we'll move back to the `#rust-content`.

**5:30-6pm UTC on #rust-community on irc.mozilla.org. EIAL (Easy IRC Access Link): https://kiwiirc.com/client/irc.mozilla.org:+6667/#rust-community**

Agenda

- Announcements - @booyaa 5mins
- #rustreach campaign - @ashleygwilliams 5mins
- Q&A for Content-o-Tron 🤖 Global Sprint 10-11th May - @booyaa 10mins

10 mins remaining

Please comment below if you wish to add anything to the agenda!

**Comment by ashleygwilliams** [comment]
potential call for blog posts: how you got into rust (use the #rustreach hashtag, the program kicks off may 15th so it might be cool to have community members write stories about how they got into rust as a way of motivation for the new participants as they start their journey)

**Comment by booyaa** [comment]
Adding this as a discussion point for the next main meeting: https://github.com/rust-community/content-o-tron/issues/42
