### ISSUE TITLE
Agenda: 22 May 2018

### ISSUE THREAD

**Issue by booyaa** [rust-community/content-team#29]
Please note we've moved back to the main community channel (`#rust-community`) to increase our reach. Once we've reached sufficient momentum we'll move back to the `#rust-content`.

**5:30-6pm UTC on #rust-community on irc.mozilla.org. EIAL (Easy IRC Access Link): https://kiwiirc.com/client/irc.mozilla.org:+6667/#rust-community**

Agenda

- Announcements - @booyaa 1mins
- Content-o-Tron roadmap v1.0.1 @booyaa 5mins
   - https://github.com/rust-community/content-o-tron/issues/55
   - action/outcome: @booyaa has promoted this roadmap as published, the old [roadmap](https://github.com/rust-community/content-o-tron/issues/2) has been retired.
- Transferring ownership of repos to the rust-community org
  - Blogging template - @booyaa 5mins - https://github.com/rust-community/content-o-tron/issues/42
  - Curation tool - https://github.com/rust-community/content-o-tron/issues/12
  - action/outcome: @booyaa has referred to this to the main team meeting next Wednesday

19 mins remaining

Please comment below if you wish to add anything to the agenda!

**Comment by o0Ignition0o** [comment]
I'll be on vacation next week, so unfortunately I won't be able to attend.
Could anyone please share the main decisions in this issue once the meeting is over ? :)
