### ISSUE TITLE
Agenda: 14 Aug 2018

### ISSUE THREAD

**Issue by booyaa** [rust-community/content-team#38]
Please note we've moved back to the main community channel (`#rust-community`) to increase our reach. Once we've reached sufficient momentum we'll move back to the `#rust-content`.

**5:30-6pm UTC on #rust-community on irc.mozilla.org. EIAL (Easy IRC Access Link): https://kiwiirc.com/client/irc.mozilla.org:+6667/#rust-community**

Meeting logs (IRC): https://mozilla.logbot.info/rust-community

**Agenda** (shortened URL to this issue: [bit.ly/2GSLLYA](http://bit.ly/2GSLLYA)

- Announcements - @booyaa 1 mins
- Discord - @booyaa 1 mins
- New Rust Site + Read Rust - @booyaa 5 mins

23 mins remaining

Please comment below if you wish to add anything to the agenda!

**Comment by wezm** [comment]
@booyaa 

> If anyoe wants to see the original email, I'll need to ask Wesley if he's okay for me to forward it on. I reckon he'll be okay

Yep that's fine.

**Comment by booyaa** [comment]
Folks here's Wesley's email: https://gist.github.com/booyaa/60f537633f9a5b45c294ba84fefef297

**Comment by booyaa** [comment]
Closed by #39
