### ISSUE TITLE
Agenda: 9 October 2018

### ISSUE THREAD

**Issue by booyaa** [rust-community/content-team#42]
**5:30-6pm UTC on the community-team\general in Discord** (https://discordapp.com/channels/442252698964721669/443773747350994945) please ask @booyaa for invites if you don't haven't joined Discord before.

**Agenda** (shortened URL to this issue: [bit.ly/2GSLLYA](http://bit.ly/2GSLLYA)

- Announcements - @booyaa 24mins
  - New meeting time

20 mins remaining

Please comment below if you wish to add anything to the agenda!

**Comment by nasa42** [comment]
* Moving the current [TWiR repo](https://github.com/cmr/this-week-in-rust) to [rust-community](https://github.com/rust-community).
* Looking into possibilities of setting up DKIM/SPF for `twir@rust-lang.org`. (related: https://github.com/cmr/this-week-in-rust/issues/714).

**Comment by booyaa** [comment]
Notes:
- @booyaa
  - Announced there's New meeting time of Monday 5pm UTC. :tada:
  - Old issues in the repo have been closed :tada:
  - Has not heard from the team invoved Editions (for the purposes of beginning blog post curation), will give them a nudge.
- @nasa42 
  - Will ask @cmr to initiate the transfer of the TWiR repo (from @cmr) to @rust-community/community-team. @booyaa also added @nasa42 as a member of the comm team (as well as a member of the TWiR team) to allow him to accept the transfer request.
 - Will contact the infra team to setup DKIM/SPF for `twir@rust-lang.org`

**Comment by booyaa** [comment]
closed by #43
