### ISSUE TITLE
Agenda: 13th February 2018

### ISSUE THREAD

**Issue by booyaa** [rust-community/content-team#6]
**5:30-6pm UTC on #rust-content on irc.mozilla.org. EIAL (Easy IRC Access Link): https://kiwiirc.com/client/irc.mozilla.org:+6667/#rust-content**
If you can't attend on the day or time, please use the team discussion [thread](https://github.com/orgs/rust-community/teams/content-team/discussions/3).

Agenda

- Housekeeping
  - Tools (team discussion, issues and repo) - @booyaa
  - Preferred format for meeting? - @Manishearth 
- Tracking our resources [link](https://github.com/orgs/rust-community/teams/content-team/discussions/2/comments/4) - @booyaa
- Rust Planet/Magazine briefing - @skade @wezm @aturon 
  - Rust Anthology
- Youtube update - @booyaa
  - Guide
  - Plan for continued maintenance

Please add any agenda items you wish to discuss.

**Comment by Manishearth** [comment]
I wonder if @skade wants to discuss their Rust Planet/Magazine idea?

Also should perhaps decide on meeting format.

**Comment by wezm** [comment]
I won't be able to attend due to time zones. If you'd like to know anything in particular about what I have set up regarding Read Read let me know an I'll provide info before the meeting.

**Comment by booyaa** [comment]
@wezm thanks, i did recall you're in the southern hemisphere. is it okay if we ask questions in the meeting [thread](https://github.com/orgs/rust-community/teams/content-team/discussions/3)? Cheers!

**Comment by wezm** [comment]
> is it okay if we ask questions in the meeting thread?

Yes by all means, ask away.

**Comment by booyaa** [comment]
Meeting has ended.
